version: "3.9"

volumes:
  nextcloud-app:
  nextcloud-db:

services:
  nextcloud-app:
    image: nextcloud:fpm-alpine
    container_name: nextcloud_app
    restart: always
    volumes:
      - nextcloud-app:/var/www/html
      - ${LOCAL_PATH_TO_FILES:-./files}:/var/www/files
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_HOME_NETWORK}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - PHP_MEMORY_LIMIT=2G
      - PHP_UPLOAD_LIMIT=16G
    depends_on:
      - nextcloud-db


  nextcloud-nginx:
    image: nginx:alpine
    container_name: nextcloud_proxy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - nextcloud-app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextcloud-app


  nextcloud-wireguard-client:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: nextcloud_wireguard_client
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${PATH_TO_WIREGUARD_CONF:-./peer_homeserver.conf}:/config/wg0.conf
    network_mode: "host"
    privileged: true
    restart: always

  nextcloud-db:
    image: mariadb
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}

  nextcloud-backup:
    image: offen/docker-volume-backup:latest
    container_name: nextcloud_backup
    restart: always
    environment:
      - BACKUP_FILENAME=backup-%Y-%m-%dT%H-%M-%S.tar.gz
      - BACKUP_LATEST_SYMLINK=backup-latest.tar.gz
      - BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS}
    volumes:
      - nextcloud-app:/backup/nextcloud-app-backup:ro
      - nextcloud-db:/backup/nextcloud-db-backup:ro
        # Mounting the Docker socket allows the script to stop and restart
        # the container during backup. You can omit this if you don't want
        # to stop the container. In case you need to proxy the socket, you can
        # also provide a location by setting `DOCKER_HOST` in the container
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${LOCAL_PATH_TO_BACKUPS-./backups}:/archive
