#!/bin/bash

# Подключаемся к MariaDB и выполняем SQL-команды
mariadb -u root -p"$MYSQL_ROOT_PASSWORD" <<EOF
CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE_1};
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE_1}.* TO '${MYSQL_USER}'@'%';

CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE_2};
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE_2}.* TO '${MYSQL_USER}'@'%';
EOF
