
version: '3'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: homecloud_wireguard
    # adds special permissions to the container so it can manage network interfaces.
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERPORT=51820
      - PEERS=homeserver,myPC,myPhone,myTablet #clients
      - INTERNAL_SUBNET=10.13.13.0 # internal WireGuard network
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - ./config:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
